### ISSUE TITLE
bump to new versions

### ISSUE THREAD

**Issue by h31p** [ToeiRei/crowdsec-overlay#10]
greetings!

cscli begined to complain:

`WARN[30-05-2023 12:50:18] Crowdsec is not the latest version. Current version is 'v1.5.1' and the latest stable version is 'v1.5.2'. Please update it!
WARN[30-05-2023 12:50:18] As a result, you will not be able to use parsers/scenarios/collections added to Crowdsec Hub after CrowdSec v1.5.2
`

crowdsec-1.5.2 was released 4 days ago, so was cs-firewall-bouncer-0.0.27 and cs-blocklist-mirror-0.0.2
can you please make approptiate new ebuilds? thanks

**Comment by ToeiRei** [comment]
Hey h31p,

I'm currently struggling to get the freebsd sources as I do not have access to those yet (I've been promised to get them since release).
The freebsd sources are the sources having the vendor files included to allow for 'offline building'  or in our case 'not breaking out of the sandbox'. - see #2

**Comment by h31p** [comment]
ok, will wait. thank you for your great and so needful work

**Comment by ToeiRei** [comment]
I updated the bouncer and the mirror ebuild so far: https://github.com/ToeiRei/crowdsec-overlay/commit/d6d805ca8db858e316bd5980eb7c75ea30ee1246 and https://github.com/ToeiRei/crowdsec-overlay/commit/dee785a796a69819da1d0b3cc6b2e1e369b88fe8 but I do not know how they'll play with the old LAPI

**Comment by ToeiRei** [comment]
Alright. I hope I got the bumps done. @mmetc on discord was so kind to publish the tags so I could finish that one. - Feel free to get in touch with me at the crowdsec discord on improving the overlay.
