### ISSUE TITLE
cs-firewall-bouncer nftables notice

### ISSUE THREAD

**Issue by h31p** [ToeiRei/crowdsec-overlay#13]
gentoo's nftables by default built without json support, causing this:

`
time="30-05-2023 15:07:08" level=warning msg="nft -j is not supported (requires 0.9.7), nftables metrics are disabled"
`

guess, it would be useful to warn (i mean elog in postinst) of the need to re-emerge nftables with 'json' use flag added.

**Comment by ToeiRei** [comment]
can add it as a requirement. Thanks for spotting

**Comment by ToeiRei** [comment]
That should do the trick, please verify
