### ISSUE TITLE
ARM build maybe?

### ISSUE THREAD

**Issue by ToeiRei** [ToeiRei/crowdsec-overlay#4]
See https://doc.crowdsec.net/docs/getting_started/install_crowdsec/#running-crowdsec-on-raspberry-pi-osraspbian

**Comment by necrose99** [comment]
https://radxa.com/

Orange pi

https://www.khadas.com , bios pxe boot over inter-webs.. 

Odriod... 

Some new boards have faster gpu/cpu  and upto 32 gigs of ram..  and some cases = or less than a full rpi4 8gig kit..
16 gigs lcd screen etc within same cost as the scalping of rpi4 on Amazon etc.. with lcd or other addition things like nvme cards etc. 

https://youtu.be/wl5H5rT87JE
Desktop/Workstation.. 80-120 arm64 cores of brutality 
Nvidia RTX gpu cards and as much ram as you care.. 
$3600 

However dev-go/gox .. 
Cheap and efficient.. 

Need pfsense (bsd) arm64 ? Run on the embedded router.. 
windows linux gox 
Gox on golang files , akin to go build with targets (Specfic) or without it will build everything for everything..  
Cgo  support however tends to be better supported on Linux or vmware Linux,  etc.
