### ISSUE TITLE
openrc service files not working correctly

### ISSUE THREAD

**Issue by g00g1** [ToeiRei/crowdsec-overlay#7]
https://github.com/ToeiRei/crowdsec-overlay/blob/810407105a9aaf256c34150c54bb778ed67fa54c/net-analyzer/cs-firewall-bouncer/files/cs-firewall-bouncer.openrc#L4

Should be `command_args="-c /etc/crowdsec/crowdsec-firewall-bouncer.yaml"`

**Comment by ToeiRei** [comment]
Good catch. Didn't check the openrc files when @necrose99 provided them.

**Comment by g00g1** [comment]
One more issue I found out is that when doing `sudo rc-service cs-firewall-bouncer` it does not exit like with others daemons started:

```bash
admin@flopster ~ $ sudo rc-service crowdsec-firewall-bouncer start
 * Caching service dependencies ...                                                                                                                                                   [ ok ]
 * Starting crowdsec ...
INFO[0000] crowdsec-firewall-bouncer v0.0.25-gentoo-pragmatic-0.0.25 

```

To fix this I have added `supervisor="supervise-daemon"` to the init.d

**Comment by ToeiRei** [comment]
Should be good now - hopefully. I take it the blocklist mirror will suffer the same problems - credits to @necrose99

**Comment by ToeiRei** [comment]
could you test the openrc for the blocklist mirror as well so we can fix this issue once and for all?

**Comment by g00g1** [comment]
> could you test the openrc for the **blocklist mirror** as well so we can fix this issue once and for all?

line:
`command_args="-c /etc/crowdsec/crowdsec-firewall-bouncer.yaml"`
must be changed to:
`command_args="-c /etc/crowdsec/crowdsec-blocklist-mirror.yaml"`

as well as line:
`supervisor="supervise-daemon"`
must be added.

**Comment by ToeiRei** [comment]
As suspected. Thanks!

**Comment by necrose99** [comment]
Np , been at 55 hours of late i haven't had a chance.
