### ISSUE TITLE
Other crowdsec builds

### ISSUE THREAD

**Issue by necrose99** [ToeiRei/crowdsec-overlay#9]
https://github.com/Necrohol/crowdsec-overlay

I added some prototypes templates  
php and the haproxy... (lua ) 
Via chat gpt for croudsec bouncers.. looks mostly promising... however likely a few issues to debug? 

With hours working.. 55 or greater.  
Trying to chew on certification/prof license renewals.. amfs or having to retesting... 
Having to slave to eat the costs etc..  work till you come home n keel over. 

Laptop is down , needs a new power jack soldered on .. 
Wich has greatly thrown in a wrench in testing ,  amoung working hours upon hours via temporary..  and car also been hitting repairs overmuch.. 

I haven't had much chance in 6 weeks or so to even bother..  you're welcome to take a run at them .. 
As i haven't had a chance to do them justice,  etc.

**Comment by ToeiRei** [comment]
Sorry, but I'd rather write those from scratch than taking poor quality / untested ebuilds in here

**Comment by necrose99** [comment]
This is the haproxy bouncer i was in process of testing prior to laptop taking a dive.  It looks of reasonable quality.. template , some ebuilds from chatgpt work others require nominal fixing..  if your Dyslexic,  the ai tool can be quite the Godsend. 

# Copyright 1999-2023 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit lua

MY_PN="cs-haproxy-bouncer"
MY_P="${MY_PN}-${PV}"

DESCRIPTION="CrowdSec bouncer module for HAProxy"
HOMEPAGE="https://github.com/crowdsecurity/cs-haproxy-bouncer"
SRC_URI="https://github.com/crowdsecurity/cs-haproxy-bouncer/archive/${PV}.tar.gz -> ${MY_P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE=""

DEPEND="
	dev-lua/lua-cjson
	dev-lua/luasocket
	net-proxy/haproxy
"
RDEPEND="${DEPEND}
	dev-lua/lua-apr"

src_unpack() {
	default
	mv "${WORKDIR}/${MY_P}" "${S}"
}

src_prepare() {
	default
	# Makefile uses gcc by default
	sed -i -e 's/gcc/$(CC)/g' "${S}/Makefile"
}

src_compile() {
	# Make sure the correct CC is used
	emake CC="$(tc-getCC)" -C "${S}"
}

src_install() {
	local luaversion=$(lua_get_api_version)

	insinto "/usr/share/lua/${luaversion}"
	doins "${S}/cs_haproxy_bouncer.lua"
}

**Comment by ToeiRei** [comment]
did you test it?

**Comment by ToeiRei** [comment]
No offense, but please - for the love of whatever you believe in - please test what you do before submitting anything. I did take the openrc file from your pull request once and it did not work. I tested your previous ebuilds and they did not work. Other people are **not** your lab rats to test out and fix your stuff.

**Comment by ToeiRei** [comment]
This is all  of the go builds so far.
